Quiz/Quiz/Models/Questions.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Quiz.Models
{
    public partial class Questions
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public int Answer { get; set; }
        public int UserAnswer { get; set; }
    }
}

Quiz/Quiz/ViewModels/QuizVM.cs
using Microsoft.AspNetCore.Mvc;
using Quiz.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quiz.ViewModels
{
    public class QuizVM
    {
        public Dictionary<int, Questions> questions { get; set; }
    }
}

Quiz/Quiz/ViewModels/ResultsVM.cs
using Microsoft.AspNetCore.Mvc;
using Quiz.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quiz.ViewModels
{
    public class ResultsVM
    {
        public int score { get; set; }

    }
}

Quiz/Quiz/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using nearHardware.Data;
using Quiz.ViewModels;

namespace Quiz.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Quiz/Quiz/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Quiz.Models;
using nearHardware.Data;
using Quiz.ViewModels;

namespace Quiz.Controllers
{
    public class QuizController : Controller
    {

        private readonly IQuestionsRepository questionsRepository;
        Dictionary<int, Questions> tenQuestions;
        public QuizController(IQuestionsRepository questionsRepository)
            => this.questionsRepository = questionsRepository;
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            tenQuestions = new Dictionary<int, Questions>();
            var dbquestions = await questionsRepository.GetAllQuestionsAsync();
            List<Questions> questions = dbquestions.ToList(); 


            for (int i = 0; i < 10; i++)
            {
                Questions question = questions.ToList()[new Random().Next(questions.ToList().Count)];
                tenQuestions.Add(question.Id, question);
                questions.Remove(question);
            }
            return View(new QuizVM { questions = tenQuestions });

        }
        [HttpPost]
        public async Task<IActionResult> Index(QuizVM quizVM)
        {
            var dbquestions = await questionsRepository.GetAllQuestionsAsync();
            int score = 0;
            foreach(Questions question in dbquestions.ToList())
            {
                if (quizVM.questions.Keys.ToList().Contains(question.Id))
                {
                    if (quizVM.questions[question.Id].UserAnswer == question.Answer)
                    {
                        score += 1;
                    }
                }
            }
            return RedirectToAction("Index", "Results", new ResultsVM { score = score });
        }
    }
}

Quiz/Quiz/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Quiz.Models;
using Quiz.ViewModels;

namespace Quiz.Controllers
{
    public class ResultsController : Controller
    {
        [HttpGet]
        public IActionResult Index(ResultsVM resultsVM)
        {

            return View(resultsVM);
        }
    }
}

Quiz/Quiz/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <h1>Quiz</h1>

    <h4>Opis</h4>
    <p>
        Aplikacja Quiz jest to aplikacja w technologi .Net Core 3.1 MVC. Aplikacja jest stroną internetową realizowaną w ramach projektu na studia z zajęć o technologiach chmurowych. Wykorzystuje ona bazę danych przechowywaną w chmurze Microsofr Azure, a platformą wdrożeniową jest Docker 20.10.8 postawiony na systemie Ubuntu 20.04.
    </p>
    <h4>CI</h4>
    <p>
        Repozytorium posiada zaimplementowany moduł gitlab CI w którym przy stworzeniu merge requesta włączany jest proces budowania aplikacji z wdrażanymi zmianami w celu uniknięcia błędów na głównej gałęzi projektu.
    </p>
    <h4>Wdrażanie</h4>
    <p>
        Aby zbudować i wdrożyć aplikację konieczny jest zainsalowany dokcer engin i docker cli. Więcej o instalacji dockera pod <a href="https://docs.docker.com/engine/">linkiem</a>. Następnie w katalogu <code>utils</code> znajduje sie skrypt <a href="https://gitlab.com/LukM88/quiz/-/blob/main/utils/pull_and_build.sh">pull_and_build.sh</a> należy go pobrać i włączyć w folderze gdzie ma być zapisana aplikacja. Skrypt pobierze wtedy całe repozytorium, zbuduje, oraz włączy aplikacje pod adresem <code>quiz.pl</code> na localhoscie. Usunie on także starsze wersje aplikacji oraz kontener <code>jwilder/nginx-proxy</code>.
    </p>
    <h5>Budowanie</h5>
    <p>
        W katalogu projektu znajduje się plik <a href="https://gitlab.com/LukM88/quiz/-/blob/main/Quiz/Dockerfile">Dockerfile</a> w którym jest zestaw instrukcji używanych do zbudowania obrazu aplikacji. Celem zbudowania obrazu należy użyć komendy <code>docker build Quiz</code> włączonej w katalogu z folderem Quiz. Aby sprawdzić czy obraz został utworzony należy użyć polecenia <code>docker image ls</code>
    </p>
    <h5> Włączenie aplikacji</h5>
    <p>
        W momencie gdy mamy już zbudowany obraz aplikacji należy użyć polecenia w celu stworzenia kontenera odpowiedzialnego za proxy:
        <code>
            <pre>docker run -d --name jwilder -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy</pre>
        </code>
        Następnie poleceniem poniżej tworzymy kontener z aplikacją: 
        <code>
            <pre>docker run -d --name quiz -e VIRTUAL_HOST=quiz.pl <nazwa /numer id obrazu></pre>
        </code>
        Zostanie wtedy utworzony kontener o nazwie quiz wystawiony pod adresem <code>quiz.pl</code>. Domyślnie ip dockera to 172.17.0.1, a kolejne kontenery wystawione w sieci są wystawiane na kolejnych numerach ip. Celem sprawdzenia adresu ip kontenera używamy polecenia <code>docker network inspect bridge</code>. aby dostac się do aplikacji na za pomocą adresu należy dodać taki wpis do pliku <code>hosts</code> w systemie użytkownika.
        <code>
            <pre>0.0.0.0    quiz.pl</pre>
        </code>
        W przypadku innej maszyny w sieci lokalnej która ma łączyć się z aplikacją należy dodać ip serwera np.
        <code>
            <pre>10.10.10.3     quiz.pl</pre>
        </code>
    </p>
    <h5> Sprawdzenie działania </h5>
    <p>
        Aby sprawdzić działający kontener należy w przeglądarce internetowaej wpisać adres ip contenera np. <code>172.17.0.2</code>.
    </p>
    <h5>Wyłączanie i usuwanie</h5>
    <p>
        Aby sprawdzić działający kontener należy w przeglądarce internetowaej wpisać adres ip contenera np. <code>172.17.0.2</code> lub w konsoli systemowej wpisać <code>docker ps</code> powinniśmy wtedy zobaczyć 2 kontenery jeden o nazwie quiz a drugi o nazwie jwilder.
    </p>
</body>

Quiz/Quiz/Views/Quiz/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model QuizVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <h1 style="text-align:center">Odpowiedz na pytania</h1>
    <div class="container p-3 mb-2 bg-primary" style="border-radius:5px; color:black">
        @using (Html.BeginForm("Index", "Quiz", "post")) 
        { 
            @foreach (var question in Model.questions)
            {
        <div class="p-3 my-3 border bg-light" style="border-radius:5px">
            @Html.Label(question.Value.Question)
            <div class="form-group">
                @Html.RadioButtonFor(m => m.questions[question.Value.Id].UserAnswer, 0)
                @Html.Label(question.Value.A)
            </div>
            <div class="form-group">
                @Html.RadioButtonFor(m => m.questions[question.Value.Id].UserAnswer, 1)
                @Html.Label(question.Value.B)
            </div>
            <div class="form-group">
                @Html.RadioButtonFor(m => m.questions[question.Value.Id].UserAnswer, 2)
                @Html.Label(question.Value.C)
            </div>
            <div class="form-group">
                @Html.RadioButtonFor(m => m.questions[question.Value.Id].UserAnswer, 3)
                @Html.Label(question.Value.D)
            </div>

        </div>
            }
            <div class="container p-3 my-3" style="align-items:center; place-items:normal">
                <input type="submit" class="btn-primary btn-outline-success" style="text-align:right;border:medium; padding:3px; border-radius:5px" value="Wyślij">
            </div>
         } 
    </div>
</body>

Quiz/Quiz/Views/Results/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ResultsVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <div class="container" style="text-align:center">
        <h1>!!!GRATULUJĘ!!!</h1>
        <h1>Twój uzyskany wynik to:</h1>
        <h1>@Model.score/10</h1>
    </div>
</body>

Quiz/Quiz/Views/Shared/_Layout.cshtml
@{ 
    ViewBag.Title = "Quiz";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-fixed-top navbar-dark bg-dark">
        <div class="container" style="width:90%">
            <div class="navbar-header">
                <a asp-controller="Home" class="navbar-brand">Quiz</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="margin:3px">
                        <a class="btn-primary btn-outline-success" style="text-align:right;border:medium; padding:3px; border-radius:5px" asp-controller="Home">Home</a>
                    </li>
                    <li style="margin:3px">
                        <a class="btn-primary btn-outline-success" style="text-align:right;border:medium; padding:3px; border-radius:5px" asp-controller="Quiz">Quiz</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content p-3 mb-2 bg-secondar">
        @RenderBody()
        <hr />
        <footer>
            <p>2021 Quiz by LukM88 &amp; Kopiel</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Quiz/Quiz/Views/User/User.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}